name: 2.0 Build

on:
  push:
    branches:
    - 2.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Use Node 11.9.0
      uses: actions/setup-node@v1
      with:
        node-version: 11.9.0
    - name: Build
      run: |
        node --version
        npm ci
    - name: Publish canary
      run: |
        echo '//registry.npmjs.org/:_authToken=${NPM_PUBLISH_TOKEN}' >> .npmrc
        date=`date +%Y%m%d%H%M%S`
        preid = "${date}-beta"
        npx lerna publish --canary major --no-push --no-git-tag-version --dist-tag beta --force-publish --preid ${preid} -y
      env:
        NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
